#!/usr/bin/env node
// Generates generated/ts/schema.ts (the `paths` and `components` types) from openapi.yaml
// with openapi-typescript. The fetch wrapper in src/client.ts is typed against it.
// Also generated/ts/languages.ts from the language registry, locales/languages.json (ADR 0028):
// the registry sits at the repository root for translators and the phone builds, and every
// TypeScript package reads it through `@corehub/contracts` (src/languages.ts).
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';
import { generatedDir, openapiPath, repoRoot } from './lib.mjs';

const outDir = path.join(generatedDir, 'ts');
const outFile = path.join(outDir, 'schema.ts');
mkdirSync(outDir, { recursive: true });

const registryFile = path.join(repoRoot, 'locales', 'languages.json');
if (!existsSync(registryFile)) {
  console.error(`contracts:generate:ts  ${registryFile} is missing (ADR 0028)`);
  process.exit(1);
}
const registry = JSON.parse(readFileSync(registryFile, 'utf8'));
const strip = (entry) =>
  Object.fromEntries(Object.entries(entry).filter(([key]) => !key.startsWith('$')));
writeFileSync(
  path.join(outDir, 'languages.ts'),
  `// GENERATED by packages/contracts/scripts/generate-ts.mjs from locales/languages.json. Do not edit.\n` +
    `/* eslint-disable */\n` +
    `export const REGISTRY = ${JSON.stringify(
      { languages: registry.languages.map(strip), pseudo: registry.pseudo.map(strip) },
      null,
      2,
    )} as const;\n`,
);

const header = `// GENERATED by packages/contracts/scripts/generate-ts.mjs from openapi.yaml. Do not edit.\n/* eslint-disable */\n`;

if (!existsSync(openapiPath)) {
  writeFileSync(
    outFile,
    `${header}// openapi.yaml was absent at generation time; the client is untyped until it exists.\n` +
      `export type paths = Record<string, never>;\nexport type components = Record<string, never>;\n` +
      `export type operations = Record<string, never>;\n`,
  );
  console.warn(
    `contracts:generate:ts  openapi.yaml absent — wrote an empty ${path.relative(process.cwd(), outFile)}`,
  );
  process.exit(0);
}

const ast = await openapiTS(new URL(`file://${openapiPath}`), {
  alphabetize: true,
  exportType: true,
  enum: false,
});
writeFileSync(outFile, header + astToString(ast));
console.log(`contracts:generate:ts  wrote ${path.relative(process.cwd(), outFile)}`);
