package hub.core.android.ui.screens

import hub.core.android.R

/*
 * Generated with the Agents II strings (apps batch 9): the words for keys the hub sends — a channel
 * setting's option, its choices, a platform's own words for an option, a hub tools group and a
 * refusal's reason. iOS looks the same keys up in agents2.*.json. Do not edit by hand.
 */
internal object Agents2Words {
    val optionLabel: Map<String, Int> = mapOf(
        "allowed_users" to R.string.agents2_chs_option_allowed_users_label,
        "unauthorized_dm_behavior" to R.string.agents2_chs_option_unauthorized_dm_behavior_label,
        "show_reasoning" to R.string.agents2_chs_option_show_reasoning_label,
        "reasoning_style" to R.string.agents2_chs_option_reasoning_style_label,
        "tool_progress" to R.string.agents2_chs_option_tool_progress_label,
        "cleanup_progress" to R.string.agents2_chs_option_cleanup_progress_label,
        "streaming" to R.string.agents2_chs_option_streaming_label,
        "reply_to_mode" to R.string.agents2_chs_option_reply_to_mode_label,
        "reactions" to R.string.agents2_chs_option_reactions_label,
        "typing_indicator" to R.string.agents2_chs_option_typing_indicator_label,
        "disable_link_previews" to R.string.agents2_chs_option_disable_link_previews_label,
        "notifications" to R.string.agents2_chs_option_notifications_label,
        "require_mention" to R.string.agents2_chs_option_require_mention_label,
        "allowed_chats" to R.string.agents2_chs_option_allowed_chats_label,
        "free_response_chats" to R.string.agents2_chs_option_free_response_chats_label,
        "group_allowed_users" to R.string.agents2_chs_option_group_allowed_users_label,
        "observe_unmentioned_group_messages" to R.string.agents2_chs_option_observe_unmentioned_group_messages_label,
        "guest_mode" to R.string.agents2_chs_option_guest_mode_label,
        "exclusive_bot_mentions" to R.string.agents2_chs_option_exclusive_bot_mentions_label,
        "allow_bots" to R.string.agents2_chs_option_allow_bots_label,
        "stt_enabled" to R.string.agents2_chs_option_stt_enabled_label,
        "stt_echo_transcripts" to R.string.agents2_chs_option_stt_echo_transcripts_label,
        "voice_auto_tts" to R.string.agents2_chs_option_voice_auto_tts_label,
        "home_channel" to R.string.agents2_chs_option_home_channel_label,
        "gateway_restart_notification" to R.string.agents2_chs_option_gateway_restart_notification_label,
        "command_menu_max" to R.string.agents2_chs_option_command_menu_max_label,
        "proxy_url" to R.string.agents2_chs_option_proxy_url_label,
        "allowed_roles" to R.string.agents2_chs_option_allowed_roles_label,
        "allowed_channels" to R.string.agents2_chs_option_allowed_channels_label,
        "free_response_channels" to R.string.agents2_chs_option_free_response_channels_label,
        "ignored_channels" to R.string.agents2_chs_option_ignored_channels_label,
        "auto_thread" to R.string.agents2_chs_option_auto_thread_label,
        "thread_require_mention" to R.string.agents2_chs_option_thread_require_mention_label,
        "no_thread_channels" to R.string.agents2_chs_option_no_thread_channels_label,
        "disable_dms" to R.string.agents2_chs_option_disable_dms_label,
        "reply_in_thread" to R.string.agents2_chs_option_reply_in_thread_label,
        "reply_broadcast" to R.string.agents2_chs_option_reply_broadcast_label,
        "strict_mention" to R.string.agents2_chs_option_strict_mention_label,
        "free_response_rooms" to R.string.agents2_chs_option_free_response_rooms_label,
        "allowed_rooms" to R.string.agents2_chs_option_allowed_rooms_label,
        "dm_mention_threads" to R.string.agents2_chs_option_dm_mention_threads_label,
        "e2ee_mode" to R.string.agents2_chs_option_e2ee_mode_label,
        "reply_mode" to R.string.agents2_chs_option_reply_mode_label,
        "require_authenticated_sender" to R.string.agents2_chs_option_require_authenticated_sender_label,
        "skip_attachments" to R.string.agents2_chs_option_skip_attachments_label,
        "poll_interval" to R.string.agents2_chs_option_poll_interval_label,
    )
    val optionHelp: Map<String, Int> = mapOf(
        "allowed_users" to R.string.agents2_chs_option_allowed_users_help,
        "unauthorized_dm_behavior" to R.string.agents2_chs_option_unauthorized_dm_behavior_help,
        "show_reasoning" to R.string.agents2_chs_option_show_reasoning_help,
        "reasoning_style" to R.string.agents2_chs_option_reasoning_style_help,
        "tool_progress" to R.string.agents2_chs_option_tool_progress_help,
        "cleanup_progress" to R.string.agents2_chs_option_cleanup_progress_help,
        "streaming" to R.string.agents2_chs_option_streaming_help,
        "reply_to_mode" to R.string.agents2_chs_option_reply_to_mode_help,
        "reactions" to R.string.agents2_chs_option_reactions_help,
        "typing_indicator" to R.string.agents2_chs_option_typing_indicator_help,
        "disable_link_previews" to R.string.agents2_chs_option_disable_link_previews_help,
        "notifications" to R.string.agents2_chs_option_notifications_help,
        "require_mention" to R.string.agents2_chs_option_require_mention_help,
        "allowed_chats" to R.string.agents2_chs_option_allowed_chats_help,
        "free_response_chats" to R.string.agents2_chs_option_free_response_chats_help,
        "group_allowed_users" to R.string.agents2_chs_option_group_allowed_users_help,
        "observe_unmentioned_group_messages" to R.string.agents2_chs_option_observe_unmentioned_group_messages_help,
        "guest_mode" to R.string.agents2_chs_option_guest_mode_help,
        "exclusive_bot_mentions" to R.string.agents2_chs_option_exclusive_bot_mentions_help,
        "allow_bots" to R.string.agents2_chs_option_allow_bots_help,
        "stt_enabled" to R.string.agents2_chs_option_stt_enabled_help,
        "stt_echo_transcripts" to R.string.agents2_chs_option_stt_echo_transcripts_help,
        "voice_auto_tts" to R.string.agents2_chs_option_voice_auto_tts_help,
        "home_channel" to R.string.agents2_chs_option_home_channel_help,
        "gateway_restart_notification" to R.string.agents2_chs_option_gateway_restart_notification_help,
        "command_menu_max" to R.string.agents2_chs_option_command_menu_max_help,
        "proxy_url" to R.string.agents2_chs_option_proxy_url_help,
        "allowed_roles" to R.string.agents2_chs_option_allowed_roles_help,
        "allowed_channels" to R.string.agents2_chs_option_allowed_channels_help,
        "free_response_channels" to R.string.agents2_chs_option_free_response_channels_help,
        "ignored_channels" to R.string.agents2_chs_option_ignored_channels_help,
        "auto_thread" to R.string.agents2_chs_option_auto_thread_help,
        "thread_require_mention" to R.string.agents2_chs_option_thread_require_mention_help,
        "no_thread_channels" to R.string.agents2_chs_option_no_thread_channels_help,
        "disable_dms" to R.string.agents2_chs_option_disable_dms_help,
        "reply_in_thread" to R.string.agents2_chs_option_reply_in_thread_help,
        "reply_broadcast" to R.string.agents2_chs_option_reply_broadcast_help,
        "strict_mention" to R.string.agents2_chs_option_strict_mention_help,
        "free_response_rooms" to R.string.agents2_chs_option_free_response_rooms_help,
        "allowed_rooms" to R.string.agents2_chs_option_allowed_rooms_help,
        "dm_mention_threads" to R.string.agents2_chs_option_dm_mention_threads_help,
        "e2ee_mode" to R.string.agents2_chs_option_e2ee_mode_help,
        "reply_mode" to R.string.agents2_chs_option_reply_mode_help,
        "require_authenticated_sender" to R.string.agents2_chs_option_require_authenticated_sender_help,
        "skip_attachments" to R.string.agents2_chs_option_skip_attachments_help,
        "poll_interval" to R.string.agents2_chs_option_poll_interval_help,
    )
    /** "<option>.<value>" → words. */
    val choice: Map<String, Int> = mapOf(
        "unauthorized_dm_behavior.pair" to R.string.agents2_chs_choice_unauthorized_dm_behavior_pair,
        "unauthorized_dm_behavior.ignore" to R.string.agents2_chs_choice_unauthorized_dm_behavior_ignore,
        "reasoning_style.code" to R.string.agents2_chs_choice_reasoning_style_code,
        "reasoning_style.blockquote" to R.string.agents2_chs_choice_reasoning_style_blockquote,
        "reasoning_style.subtext" to R.string.agents2_chs_choice_reasoning_style_subtext,
        "tool_progress.off" to R.string.agents2_chs_choice_tool_progress_off,
        "tool_progress.new" to R.string.agents2_chs_choice_tool_progress_new,
        "tool_progress.all" to R.string.agents2_chs_choice_tool_progress_all,
        "tool_progress.verbose" to R.string.agents2_chs_choice_tool_progress_verbose,
        "reply_to_mode.off" to R.string.agents2_chs_choice_reply_to_mode_off,
        "reply_to_mode.first" to R.string.agents2_chs_choice_reply_to_mode_first,
        "reply_to_mode.all" to R.string.agents2_chs_choice_reply_to_mode_all,
        "notifications.important" to R.string.agents2_chs_choice_notifications_important,
        "notifications.all" to R.string.agents2_chs_choice_notifications_all,
        "allow_bots.none" to R.string.agents2_chs_choice_allow_bots_none,
        "allow_bots.all" to R.string.agents2_chs_choice_allow_bots_all,
        "allow_bots.mentions" to R.string.agents2_chs_choice_allow_bots_mentions,
        "e2ee_mode.off" to R.string.agents2_chs_choice_e2ee_mode_off,
        "e2ee_mode.optional" to R.string.agents2_chs_choice_e2ee_mode_optional,
        "e2ee_mode.required" to R.string.agents2_chs_choice_e2ee_mode_required,
        "reply_mode.off" to R.string.agents2_chs_choice_reply_mode_off,
        "reply_mode.thread" to R.string.agents2_chs_choice_reply_mode_thread,
    )
    /** "<platform>.option.<option>.label|help" and "<platform>.list_placeholder" → the platform's own words. */
    val platform: Map<String, Int> = mapOf(
        "discord.option.allowed_users.label" to R.string.agents2_chs_platform_discord_option_allowed_users_label,
        "discord.option.allowed_users.help" to R.string.agents2_chs_platform_discord_option_allowed_users_help,
        "discord.option.require_mention.label" to R.string.agents2_chs_platform_discord_option_require_mention_label,
        "discord.option.require_mention.help" to R.string.agents2_chs_platform_discord_option_require_mention_help,
        "discord.option.home_channel.label" to R.string.agents2_chs_platform_discord_option_home_channel_label,
        "discord.option.home_channel.help" to R.string.agents2_chs_platform_discord_option_home_channel_help,
        "discord.option.reactions.label" to R.string.agents2_chs_platform_discord_option_reactions_label,
        "discord.option.reactions.help" to R.string.agents2_chs_platform_discord_option_reactions_help,
        "discord.list_placeholder" to R.string.agents2_chs_platform_discord_list_placeholder,
        "slack.option.allowed_users.label" to R.string.agents2_chs_platform_slack_option_allowed_users_label,
        "slack.option.allowed_users.help" to R.string.agents2_chs_platform_slack_option_allowed_users_help,
        "slack.option.require_mention.label" to R.string.agents2_chs_platform_slack_option_require_mention_label,
        "slack.option.require_mention.help" to R.string.agents2_chs_platform_slack_option_require_mention_help,
        "slack.option.home_channel.label" to R.string.agents2_chs_platform_slack_option_home_channel_label,
        "slack.option.home_channel.help" to R.string.agents2_chs_platform_slack_option_home_channel_help,
        "slack.option.reactions.label" to R.string.agents2_chs_platform_slack_option_reactions_label,
        "slack.option.reactions.help" to R.string.agents2_chs_platform_slack_option_reactions_help,
        "slack.list_placeholder" to R.string.agents2_chs_platform_slack_list_placeholder,
        "matrix.option.allowed_users.label" to R.string.agents2_chs_platform_matrix_option_allowed_users_label,
        "matrix.option.allowed_users.help" to R.string.agents2_chs_platform_matrix_option_allowed_users_help,
        "matrix.option.require_mention.label" to R.string.agents2_chs_platform_matrix_option_require_mention_label,
        "matrix.option.require_mention.help" to R.string.agents2_chs_platform_matrix_option_require_mention_help,
        "matrix.option.home_channel.label" to R.string.agents2_chs_platform_matrix_option_home_channel_label,
        "matrix.option.home_channel.help" to R.string.agents2_chs_platform_matrix_option_home_channel_help,
        "matrix.option.reactions.label" to R.string.agents2_chs_platform_matrix_option_reactions_label,
        "matrix.option.reactions.help" to R.string.agents2_chs_platform_matrix_option_reactions_help,
        "matrix.section.groups" to R.string.agents2_chs_platform_matrix_section_groups,
        "matrix.list_placeholder" to R.string.agents2_chs_platform_matrix_list_placeholder,
        "mattermost.option.allowed_users.label" to R.string.agents2_chs_platform_mattermost_option_allowed_users_label,
        "mattermost.option.allowed_users.help" to R.string.agents2_chs_platform_mattermost_option_allowed_users_help,
        "mattermost.option.require_mention.label" to R.string.agents2_chs_platform_mattermost_option_require_mention_label,
        "mattermost.option.require_mention.help" to R.string.agents2_chs_platform_mattermost_option_require_mention_help,
        "mattermost.option.home_channel.label" to R.string.agents2_chs_platform_mattermost_option_home_channel_label,
        "mattermost.option.home_channel.help" to R.string.agents2_chs_platform_mattermost_option_home_channel_help,
        "mattermost.list_placeholder" to R.string.agents2_chs_platform_mattermost_list_placeholder,
        "email.option.allowed_users.label" to R.string.agents2_chs_platform_email_option_allowed_users_label,
        "email.option.allowed_users.help" to R.string.agents2_chs_platform_email_option_allowed_users_help,
        "email.option.home_channel.label" to R.string.agents2_chs_platform_email_option_home_channel_label,
        "email.option.home_channel.help" to R.string.agents2_chs_platform_email_option_home_channel_help,
        "email.section.access" to R.string.agents2_chs_platform_email_section_access,
        "email.section.media" to R.string.agents2_chs_platform_email_section_media,
        "email.list_placeholder" to R.string.agents2_chs_platform_email_list_placeholder,
    )
    val section: Map<String, Int> = mapOf(
        "access" to R.string.agents2_chs_section_access,
        "replies" to R.string.agents2_chs_section_replies,
        "groups" to R.string.agents2_chs_section_groups,
        "media" to R.string.agents2_chs_section_media,
        "advanced" to R.string.agents2_chs_section_advanced,
    )
    val group: Map<String, Int> = mapOf(
        "tasks" to R.string.agents2_hub_group_tasks,
        "schedules" to R.string.agents2_hub_group_schedules,
        "conversations" to R.string.agents2_hub_group_conversations,
        "notifications" to R.string.agents2_hub_group_notifications,
        "workflows" to R.string.agents2_hub_group_workflows,
        "files" to R.string.agents2_hub_group_files,
        "devices" to R.string.agents2_hub_group_devices,
    )
    val groupAbout: Map<String, Int> = mapOf(
        "tasks" to R.string.agents2_hub_group_about_tasks,
        "schedules" to R.string.agents2_hub_group_about_schedules,
        "conversations" to R.string.agents2_hub_group_about_conversations,
        "notifications" to R.string.agents2_hub_group_about_notifications,
        "workflows" to R.string.agents2_hub_group_about_workflows,
        "files" to R.string.agents2_hub_group_about_files,
        "devices" to R.string.agents2_hub_group_about_devices,
    )
    val reason: Map<String, Int> = mapOf(
        "hub_tools_no_live_run" to R.string.agents2_hub_reason_hub_tools_no_live_run,
        "hub_tools_run_ambiguous" to R.string.agents2_hub_reason_hub_tools_run_ambiguous,
        "hub_tools_tool_off" to R.string.agents2_hub_reason_hub_tools_tool_off,
        "path_outside_profile" to R.string.agents2_hub_reason_path_outside_profile,
        "forbidden" to R.string.agents2_hub_reason_forbidden,
        "not_found" to R.string.agents2_hub_reason_not_found,
        "validation_failed" to R.string.agents2_hub_reason_validation_failed,
        "hub_tools_sender_not_linked" to R.string.agents2_hub_reason_hub_tools_sender_not_linked,
        "hub_tools_sender_no_access" to R.string.agents2_hub_reason_hub_tools_sender_no_access,
        "hub_tools_group_chat" to R.string.agents2_hub_reason_hub_tools_group_chat,
    )
    val unavailable: Map<String, Int> = mapOf(
        "runtime_absent" to R.string.agents2_hub_unavailable_runtime_absent,
        "hermes_profile_absent" to R.string.agents2_hub_unavailable_hermes_profile_absent,
    )
}
